import type { AppUser, Asset, AssetTransaction, BrandingSettings, Department, EmailSettings, Site } from './types'

export const seedAssets: Asset[] = [
  {
    id: 1,
    code: 'TS-2024-001',
    name: 'MacBook Pro 14” M3',
    category: 'Laptop',
    serial: 'FVFGH20PLK',
    department: 'Marketing',
    location: 'VP Hà Nội · Tầng 3',
    assignedTo: 'Nguyễn Minh Anh',
    purchaseDate: '2024-01-12',
    purchaseCost: 46500000,
    status: 'Đang sử dụng',
    icon: 'laptop',
    manufacturer: 'Apple',
    model: 'MacBook Pro 14-inch M3',
    cpu: 'Apple M3 8-core',
    ram: '16 GB',
    storage: 'SSD 512 GB',
    operatingSystem: 'macOS 15',
    ipAddress: '10.10.3.24',
    macAddress: 'A4:83:E7:21:9C:10',
  },
  {
    id: 2,
    code: 'TS-2024-002',
    name: 'Dell UltraSharp U2723QE',
    category: 'Màn hình',
    serial: 'CN0F3G4H28',
    department: 'Kỹ thuật',
    location: 'VP Hà Nội · Tầng 4',
    assignedTo: 'Trần Đức Long',
    purchaseDate: '2024-01-18',
    purchaseCost: 13900000,
    status: 'Đang sử dụng',
    icon: 'monitor',
    manufacturer: 'Dell',
    model: 'U2723QE',
  },
  {
    id: 3,
    code: 'TS-2023-087',
    name: 'Máy in HP LaserJet Pro',
    category: 'Máy in',
    serial: 'VNB3J82350',
    department: 'Hành chính',
    location: 'VP Hà Nội · Tầng 2',
    assignedTo: 'Phòng Hành chính',
    purchaseDate: '2023-08-21',
    purchaseCost: 8900000,
    status: 'Bảo trì',
    icon: 'printer',
  },
  {
    id: 4,
    code: 'TS-2024-014',
    name: 'iPhone 15 Pro 256GB',
    category: 'Mobile',
    serial: 'F2LXQ8M4YH',
    department: 'Kinh doanh',
    location: 'VP Hồ Chí Minh',
    assignedTo: 'Lê Hoàng Nam',
    purchaseDate: '2024-03-06',
    purchaseCost: 28990000,
    status: 'Đang sử dụng',
    assignmentType: 'Cho mượn',
    dueDate: '2026-08-25',
    icon: 'phone',
  },
  {
    id: 5,
    code: 'TS-2022-156',
    name: 'Ghế công thái học Ergohuman',
    category: 'Nội thất',
    serial: 'ERGO-22-156',
    department: 'Kỹ thuật',
    location: 'VP Hà Nội · Tầng 4',
    assignedTo: 'Chưa gán',
    purchaseDate: '2022-11-11',
    purchaseCost: 12400000,
    status: 'Sẵn sàng',
    icon: 'chair',
  },
  {
    id: 6,
    code: 'TS-2023-102',
    name: 'Cisco Catalyst 9200L',
    category: 'Switch',
    serial: 'FCW2721L0A8',
    department: 'IT',
    location: 'Phòng Server · Tầng 1',
    assignedTo: 'Bộ phận IT',
    purchaseDate: '2023-09-14',
    purchaseCost: 78500000,
    status: 'Đang sử dụng',
    icon: 'switch',
    manufacturer: 'Cisco',
    model: 'Catalyst C9200L-24T-4G',
    ipAddress: '10.10.1.2',
    macAddress: '40:55:39:A0:18:22',
  },
  {
    id: 7,
    code: 'TS-2021-034',
    name: 'Lenovo ThinkPad X1',
    category: 'Laptop',
    serial: 'PF2CZ81M',
    department: 'Kế toán',
    location: 'VP Hà Nội · Tầng 3',
    assignedTo: 'Phạm Thu Hà',
    purchaseDate: '2021-05-20',
    purchaseCost: 38400000,
    status: 'Hỏng',
    icon: 'laptop',
    manufacturer: 'Lenovo',
    model: 'ThinkPad X1 Carbon Gen 9',
    cpu: 'Intel Core i7-1165G7',
    ram: '16 GB',
    storage: 'SSD 1 TB',
    operatingSystem: 'Windows 11 Pro',
    ipAddress: '10.10.3.42',
    macAddress: '8C:8D:28:73:2A:11',
  },
  {
    id: 8,
    code: 'TS-2024-026',
    name: 'Samsung Galaxy Tab S9',
    category: 'Tablet',
    serial: 'R52W90AB8LX',
    department: 'Kinh doanh',
    location: 'Kho Tổng · Kệ A02',
    assignedTo: 'Chưa gán',
    purchaseDate: '2024-04-15',
    purchaseCost: 19990000,
    status: 'Sẵn sàng',
    icon: 'tablet',
  },
  {
    id: 9,
    code: 'SW-2026-011',
    name: 'Microsoft 365 Business',
    category: 'Phần mềm & Bản quyền',
    serial: 'LIC-M365-120U',
    department: 'IT',
    location: 'Microsoft Cloud',
    assignedTo: '120 người dùng',
    purchaseDate: '2026-01-05',
    purchaseCost: 432000000,
    status: 'Đang sử dụng',
    icon: 'software',
  },
  {
    id: 10,
    code: 'SO-2026-004',
    name: 'Chứng chỉ SSL Wildcard',
    category: 'Tài sản số & Dữ liệu',
    serial: 'CERT-WILD-2026',
    department: 'IT',
    location: 'Kho chứng chỉ số',
    assignedTo: 'Bộ phận IT',
    purchaseDate: '2026-02-15',
    purchaseCost: 7200000,
    status: 'Đang sử dụng',
    icon: 'digital',
  },
  {
    id: 11,
    code: 'BYOD-2026-018',
    name: 'MacBook Air M4 cá nhân',
    category: 'Thiết bị BYOD',
    serial: 'BYOD-C02M4A18',
    department: 'Marketing',
    location: 'Ngoài văn phòng',
    assignedTo: 'Vũ Thanh Mai',
    purchaseDate: '2026-04-02',
    purchaseCost: 0,
    status: 'Đang sử dụng',
    icon: 'byod',
  },
  {
    id: 12,
    code: 'PK-2026-001',
    name: 'Tai nghe Jabra Evolve2 65',
    category: 'Tai nghe',
    serial: 'JAB-E265-0182',
    department: 'Kinh doanh',
    location: 'Văn phòng Hà Nội · Tầng 3',
    assignedTo: 'Lê Hoàng Nam',
    purchaseDate: '2026-03-12',
    purchaseCost: 5200000,
    status: 'Đang sử dụng',
    icon: 'headphones',
    manufacturer: 'Jabra',
    model: 'Evolve2 65',
  },
  {
    id: 13,
    code: 'PK-2026-002',
    name: 'Bàn phím Logitech MX Keys S',
    category: 'Bàn phím',
    serial: 'LOG-MXK-7291',
    department: 'Kỹ thuật',
    location: 'Văn phòng Hà Nội · Tầng 4',
    assignedTo: 'Trần Đức Long',
    purchaseDate: '2026-03-14',
    purchaseCost: 2890000,
    status: 'Đang sử dụng',
    icon: 'keyboard',
    manufacturer: 'Logitech',
    model: 'MX Keys S',
  },
  {
    id: 14,
    code: 'PK-2026-003',
    name: 'Chuột Logitech MX Master 3S',
    category: 'Chuột',
    serial: 'LOG-MX3S-9104',
    department: 'Marketing',
    location: 'Văn phòng Hà Nội · Tầng 3',
    assignedTo: 'Nguyễn Minh Anh',
    purchaseDate: '2026-03-14',
    purchaseCost: 2490000,
    status: 'Đang sử dụng',
    icon: 'mouse',
    manufacturer: 'Logitech',
    model: 'MX Master 3S',
  },
  {
    id: 15,
    code: 'PK-2026-004',
    name: 'Webcam Logitech Brio 4K',
    category: 'Webcam',
    serial: 'LOG-BRIO-4420',
    department: 'Hành chính',
    location: 'Văn phòng Hà Nội · Tầng 2',
    assignedTo: 'Phòng Hành chính',
    purchaseDate: '2026-04-06',
    purchaseCost: 4650000,
    status: 'Đang sử dụng',
    icon: 'webcam',
    manufacturer: 'Logitech',
    model: 'Brio 4K',
  },
  {
    id: 16,
    code: 'PK-2026-005',
    name: 'Dock Dell WD22TB4',
    category: 'Dock chuyển đổi',
    serial: 'DELL-WD22-0621',
    department: 'IT',
    location: 'Kho Tổng',
    assignedTo: 'Chưa gán',
    purchaseDate: '2026-05-10',
    purchaseCost: 6990000,
    status: 'Sẵn sàng',
    icon: 'dock',
    manufacturer: 'Dell',
    model: 'WD22TB4',
  },
  {
    id: 17,
    code: 'PK-2026-006',
    name: 'Sạc MacBook USB-C 96W',
    category: 'Sạc & Adapter',
    serial: 'APL-96W-1185',
    department: 'IT',
    location: 'Kho Tổng · Kệ P01',
    assignedTo: 'Chưa gán',
    purchaseDate: '2026-05-10',
    purchaseCost: 2190000,
    status: 'Sẵn sàng',
    icon: 'charger',
    manufacturer: 'Apple',
    model: 'USB-C 96W',
  },
  {
    id: 18,
    code: 'PK-2026-007',
    name: 'Hub USB-C Anker 555',
    category: 'Hub & Cáp kết nối',
    serial: 'ANK-555-3750',
    department: 'IT',
    location: 'Kho Tổng · Kệ P01',
    assignedTo: 'Chưa gán',
    purchaseDate: '2026-05-18',
    purchaseCost: 1890000,
    status: 'Sẵn sàng',
    icon: 'hub',
    manufacturer: 'Anker',
    model: 'PowerExpand 555',
  },
  {
    id: 19,
    code: 'PK-2026-008',
    name: 'SSD di động Samsung T7 1TB',
    category: 'Ổ lưu trữ ngoài',
    serial: 'SAM-T7-8829',
    department: 'IT',
    location: 'Kho Tổng · Tủ bảo mật',
    assignedTo: 'Bộ phận IT',
    purchaseDate: '2026-06-02',
    purchaseCost: 2790000,
    status: 'Đang sử dụng',
    icon: 'drive',
    manufacturer: 'Samsung',
    model: 'Portable SSD T7',
    storage: 'SSD 1 TB',
  },
]

export const departments = ['Tất cả phòng ban', 'Kỹ thuật', 'Marketing', 'Kinh doanh', 'Kế toán', 'Hành chính', 'IT']
export const categories = [
  'Laptop',
  'PC / Desktop',
  'Màn hình',
  'Mobile',
  'Tablet',
  'Server',
  'Switch',
  'Firewall',
  'Router / Wi-Fi',
  'UPS',
  'NAS / Storage',
  'Máy in',
  'Máy chấm công',
  'Camera',
  'Tai nghe',
  'Bàn phím',
  'Chuột',
  'Webcam',
  'Dock chuyển đổi',
  'Sạc & Adapter',
  'Hub & Cáp kết nối',
  'Ổ lưu trữ ngoài',
  'Phần mềm & Bản quyền',
  'Tài sản số & Dữ liệu',
  'Thiết bị BYOD',
  'Nội thất',
  'Khác',
]

export const seedDepartments: Department[] = [
  { id: 1, name: 'Kỹ thuật', code: 'TECH', manager: 'Trần Đức Long' },
  { id: 2, name: 'Marketing', code: 'MKT', manager: 'Nguyễn Minh Anh' },
  { id: 3, name: 'Kinh doanh', code: 'SALES', manager: 'Lê Hoàng Nam' },
  { id: 4, name: 'Kế toán', code: 'ACC', manager: 'Phạm Thu Hà' },
  { id: 5, name: 'Hành chính', code: 'ADMIN', manager: 'Nguyễn Thu Hương' },
  { id: 6, name: 'IT', code: 'IT', manager: 'Trần Đức Long' },
]

export const seedSites: Site[] = [
  { id: 1, name: 'Văn phòng Hà Nội', code: 'HN', address: 'Hà Nội' },
  { id: 2, name: 'Văn phòng Hồ Chí Minh', code: 'HCM', address: 'TP. Hồ Chí Minh' },
  { id: 3, name: 'Kho Tổng', code: 'KHO', address: 'Hà Nội' },
  { id: 4, name: 'Phòng Server', code: 'DC01', address: 'Văn phòng Hà Nội · Tầng 1' },
]

export const seedEmailSettings: EmailSettings = {
  senderName: 'Bộ phận Quản lý tài sản',
  replyTo: 'it-assets@company.vn',
  cc: '',
  subjectTemplate: 'Biên bản bàn giao tài sản {{asset_code}}',
}

export const seedBrandingSettings: BrandingSettings = {
  appName: 'AssetFlow',
  companyName: 'Công ty của bạn',
  companyAddress: 'Địa chỉ công ty',
  handoverDepartment: 'Bộ phận IT / Quản lý tài sản',
  handoverFormCode: 'AF-BB-01',
  tagline: 'Quản lý tài sản',
  primaryColor: '#5b55d9',
  logoDataUrl: '',
}

export const seedUsers: AppUser[] = [
  {
    id: 1,
    username: 'admin',
    name: 'Quản trị viên',
    email: 'admin@localhost',
    role: 'Admin',
    departmentScope: ['*'],
    mustChangePassword: true,
  },
]

export const seedTransactions: AssetTransaction[] = [
  {
    id: 101,
    assetId: 1,
    assetCode: 'TS-2024-001',
    assetName: 'MacBook Pro 14” M3',
    type: 'Cấp phát',
    from: 'Kho Tổng',
    to: 'Nguyễn Minh Anh',
    performedBy: 'Nguyễn Linh',
    date: '2026-08-18T08:20:00',
    note: 'Cấp phát cho nhân viên Marketing',
  },
  {
    id: 102,
    assetId: 8,
    assetCode: 'TS-2024-026',
    assetName: 'Samsung Galaxy Tab S9',
    type: 'Thu hồi',
    from: 'Hoàng Anh Tuấn',
    to: 'Kho Tổng · Kệ A02',
    performedBy: 'Nguyễn Linh',
    date: '2026-08-17T15:40:00',
    note: 'Thu hồi khi nhân viên nghỉ việc',
  },
  {
    id: 103,
    assetId: 6,
    assetCode: 'TS-2023-102',
    assetName: 'Cisco Catalyst 9200L',
    type: 'Điều chuyển',
    from: 'Kho Tổng',
    to: 'Phòng Server · Tầng 1',
    performedBy: 'Trần Đức Long',
    date: '2026-08-16T10:10:00',
    note: 'Lắp đặt tại phòng máy chủ',
  },
  {
    id: 104,
    assetId: 4,
    assetCode: 'TS-2024-014',
    assetName: 'iPhone 15 Pro 256GB',
    type: 'Nhập kho',
    from: 'Nhà cung cấp',
    to: 'Kho Tổng',
    performedBy: 'Nguyễn Linh',
    date: '2026-08-15T09:05:00',
    note: 'Nhập theo PO-2026-018',
  },
]
